name: temoa-py3.11
channels:
    - defaults
    - conda-forge
dependencies:
    # Requirements for core model functionality
    - python>=3.11
    - pyomo>=6.4
    - xlwt
    - ipython
    - matplotlib
    - pandas
    - numpy
    - scipy
    - joblib
    - salib
    - pydoe
    - pyutilib
    - glpk
    - python-graphviz
    - ipykernel
    - jupyter
    - seaborn
    - tabulate
    - xlsxwriter
    - plotly
    - pyam
    # Below required to update documentation
    - sphinx
    - sphinx_rtd_theme
    - sphinxcontrib-htmlhelp
    - sphinxcontrib-serializinghtml
    - sphinxcontrib-bibtex
    # cbc solver below cannot be installed via Conda on Windows
    - coincbc
