scenario = "reference"
scenario_mode = "myopic"
input_database = "/trace/group/adams/cwade2/temoa_v4/servers/current_policies_noIRA_52_week_retire.sqlite"
output_database = "/trace/group/adams/cwade2/temoa_v4/servers/current_policies_noIRA_52_week_retire.sqlite"
solver_name = "gurobi"
save_lp_file = false
save_duals = true
save_excel = false
neos = false
time_sequencing = "seasonal_timeslices"
reserve_margin = "static"
output_threshold_capacity = 10.0
output_threshold_activity = 10.0
output_threshold_emission = 10.0
output_threshold_cost = 10.0

[myopic]
view_depth = 1
step_size = 1
